# Generated by Django 6.0.3 on 2026-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('other', 'Other')], default='other', max_length=20)),
                ('link_type', models.CharField(choices=[('redirect', 'Redirect Link'), ('product', 'Product Link')], max_length=20)),
                ('link_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='redirects/')),
                ('logo_svg', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
